# .github/workflows/check-license-headers.yml

name: Check Source File Headers

on:
  push:
    branches: 
    - "main"
    - "test"
  pull_request:
    branches: 
    - "main"
    - "test"
  workflow_dispatch:

jobs:
  verify_headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check License Headers
        uses: viperproject/check-license-header@v2.0.3
        with:
          path: .
          config: '.github/license-config.json'
          strict: false
